version: '3.4'
services:
  dt:
    image: "nginx:latest"
    container_name: jarvans_com_nginx
    volumes:
      - ./docs/:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
          - "4005:80"
